# Generated by Django 4.2 on 2025-02-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='threat_type',
            field=models.CharField(choices=[('intrusion', 'Intrusion'), ('violence', 'Violence'), ('theft', 'Theft'), ('Shoplifting', 'Shoplifting'), ('Burglary', 'Burglary'), ('Stealing', 'Stealing'), ('normal', 'normal'), ('Vandalism', 'Vandalism'), ('Robbery', 'Robbery'), ('suspicious', 'Suspicious Activity')], max_length=50),
        ),
    ]
