# Generated by Django 4.2 on 2025-02-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_alter_alert_threat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='timestamp_vid',
            field=models.TextField(default=89, verbose_name=''),
            preserve_default=False,
        ),
    ]
