# Generated by Django 4.2 on 2025-02-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_alert_timestamp_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp_vid',
            field=models.DateTimeField(),
        ),
    ]
