# Generated by Django 4.2 on 2025-02-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0004_alter_alert_timestamp_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp_vid',
            field=models.TimeField(blank=True, help_text='Video frame timestamp (HH:MM:SS.mmm)', null=True),
        ),
    ]
