# Generated by Django 4.2 on 2025-02-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0005_alter_alert_timestamp_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp_vid',
            field=models.TimeField(help_text='Video frame timestamp (HH:MM:SS.mmm)'),
        ),
    ]
